### ISSUE TITLE
Does not work in internet explorer

### ISSUE THREAD

**Issue by figassis** [Helvio88/angular-xlsx-model#1]
You get an error on xlsx-model.js line 86: Object doesn't support property or method 'readAsBinaryString'

I then tried this workaround: http://stackoverflow.com/a/32665193/1324921

And I got an error on line 67: Unable to get property 'target' of undefined or null reference

You can replicate this with the Plunker you listed on your repo.

**Comment by Helvio88** [comment]
Hello, figassis. That is confirmed, but since that's a IE limitation, I will not build a workaround. IE is obsolete as of now, and we have to let it die instead of making efforts to keep it alive. I will add this information on the README.md file. Thanks!

**Comment by figassis** [comment]
That’s true. IE is obsolete, but it is also often a main requirement for our projects and MS can fund mediocre IE to outlast our careers.
js-xlsx allows you to use base64 instead, which FileReader encodes automatically.
Thanks!

Assis
