### ISSUE TITLE
Receiving error: Uncaught ReferenceError: XLSX is not defined     at FileReader.reader.onload (xlsx-model.js:68)

### ISSUE THREAD

**Issue by bgoncal** [Helvio88/angular-xlsx-model#4]
Uncaught ReferenceError: XLSX is not defined
    at FileReader.reader.onload (xlsx-model.js:68)

**Comment by Helvio88** [comment]
Can you reproduce the issue in a plunkr?

**Comment by bgoncal** [comment]
I just used your plunker files and it worked well, sorry

**Comment by Helvio88** [comment]
Valeu!
